### ISSUE TITLE
day05 creating form todo

### ISSUE THREAD

**Issue by kocsisttibor** [greenfox-academy/kocsisttibor#1]
- [ ]  fix male/female radio buttons
- [ ] set min year for birth of year
- [ ] make checkbox labels clickable
- [ ] change hint text color in select and textarea items
